ALTER TABLE EMPLEATS
  ADD CONSTRAINT FK_empl_empl FOREIGN KEY(cap) REFERENCES EMPLEATS(numemp);
ALTER TABLE EMPLEATS
  ADD CONSTRAINT FK_empl_ofic FOREIGN KEY(oficina) REFERENCES OFICINES(oficina) ON DELETE SET NULL;
ALTER TABLE OFICINES
  ADD CONSTRAINT FK_ofic_empl FOREIGN KEY(dir) REFERENCES EMPLEATS(numemp) ON DELETE SET NULL;
ALTER TABLE COMANDA
  ADD CONSTRAINT FK_comanda_empl FOREIGN KEY(rep_ven) REFERENCES EMPLEATS(numemp) ON DELETE RESTRICT;
ALTER TABLE LINIA_COMANDA
  ADD CONSTRAINT FK_lincomanda_com FOREIGN KEY(numcomanda) REFERENCES COMANDA(numcomanda) ON DELETE RESTRICT;
ALTER TABLE COMANDA
  ADD CONSTRAINT FK_comanda_client FOREIGN KEY(clie) REFERENCES CLIENTS(numclie);
ALTER TABLE LINIA_COMANDA
  ADD CONSTRAINT FK_lincomanda_prod FOREIGN KEY(codfab, codprod) REFERENCES PRODUCTES(codfab, codprod);
